### ISSUE TITLE
egohands setup error

### ISSUE THREAD

**Issue by monajalal** [GustavZ/deeptraining_hands#2]
I get the following error when setting up for egohands. Can you please share the fix?

```
4795 egohands/_LABELLED_SAMPLES/CHESS_OFFICE_T_H_frame_2669.jpg
4796 egohands/_LABELLED_SAMPLES/CHESS_OFFICE_T_H_frame_2186.jpg
4797 egohands/_LABELLED_SAMPLES/CHESS_OFFICE_T_H_frame_1563.jpg
4798 egohands/_LABELLED_SAMPLES/CHESS_OFFICE_T_H_frame_0262.jpg
4799 egohands/_LABELLED_SAMPLES/CHESS_OFFICE_T_H_frame_1768.jpg
4800 egohands/_LABELLED_SAMPLES/CHESS_OFFICE_T_H_frame_1332.jpg
>   done scanning director  CHESS_OFFICE_T_H
Train/Eval content generation complete!
Traceback (most recent call last):
  File "egohands_setup.py", line 272, in <module>
    main()
  File "egohands_setup.py", line 266, in main
    download_egohands_dataset(EGOHANDS_DATASET_URL, EGO_HANDS_FILE)
  File "egohands_setup.py", line 236, in download_egohands_dataset
    extract_folder(dataset_path)
  File "egohands_setup.py", line 219, in extract_folder
    rename_files("egohands/_LABELLED_SAMPLES/")
  File "egohands_setup.py", line 210, in rename_files
    generate_csv_files("egohands/_LABELLED_SAMPLES/")
  File "egohands_setup.py", line 191, in generate_csv_files
    split_data_test_eval_train("egohands/_LABELLED_SAMPLES/")
  File "egohands_setup.py", line 182, in split_data_test_eval_train
    generate_label_files("data/")
  File "egohands_setup.py", line 129, in generate_label_files
    if(f.split(".")[1] == "csv"):
IndexError: list index out of range
```

**Comment by abdelazizmirasoft** [comment]
Did you solve that issue?
